version: '3'

services:
  nodejs:
    build: .
    command: node app.js
    container_name: swvl-nodejs
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo
    container_name: swvl-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    env_file:
      - .env
